"""relate users to products

Revision ID: 89fd52dc68c6
Revises: 9c650dedbab2
Create Date: 2024-12-29 20:42:11.607063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '89fd52dc68c6'
down_revision: Union[str, None] = '9c650dedbab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_uid')
    # ### end Alembic commands ###
